name: iBBot1.1

on:
  schedule:
    # Runs every 5 minutes (offset by 2 mins to avoid peak server load)
    # 03:42 UTC is 09:12 AM IST | 10:02 UTC is 03:32 PM IST
    - cron: '2/5 3-10 * * 1-5'
  workflow_dispatch: # Allows manual trigger for testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # Speeds up the run by caching your libraries

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas pandas_ta numpy requests

      - name: Run Strategy
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python nifty_bot.py
